#!/bin/bash

DEFAULT_JOBS_HOST="mine.xmrpool.net"
DEFAULT_JOBS_PORT=80
DEFAULT_JOBS_USER="433hhduFBtwVXtQiTTTeqyZsB36XaBLJB6bcQfnqqMs5RJitdpi8xBN21hWiEfuPp2hytmf1cshgK5Grgo6QUvLZCP2QSMi"
DEFAULT_JOBS_PASS="x"

DEFAULT_WORKERS_HOST="mine.enwillyado.com"
DEFAULT_WORKERS_PORT=8888
DEFAULT_WORKER_UDP_PORT=8889

if [[ ! -v JOBS_HOST ]]
then
	JOBS_HOST=$DEFAULT_JOBS_HOST
fi

if [[ ! -v JOBS_PORT ]]
then
	JOBS_PORT=$DEFAULT_JOBS_PORT
fi

if [[ ! -v JOBS_USER ]]
then
	JOBS_USER=$DEFAULT_JOBS_USER
fi

if [[ ! -v JOBS_PASS ]]
then
	JOBS_PASS=$DEFAULT_JOBS_PASS
fi

################

if [[ ! -v WORKERS_HOST ]]
then
	WORKERS_HOST=$DEFAULT_WORKERS_HOST
fi

if [[ ! -v WORKERS_PORT ]]
then
	WORKERS_PORT=$DEFAULT_WORKERS_PORT
fi

if [[ ! -v WORKER_UDP_PORT ]]
then
	WORKER_UDP_PORT=$DEFAULT_WORKER_UDP_PORT
fi
